[cleanup] move reflect-metadata import in index.ts
Since we use vscode organizeImports, the reflect-metadata import could
be reorder after sprotty import.

This reorder trigger a runtime error :
TypeError: Reflect.hasOwnMetadata is not a function"

We move this import in root index.ts as workaround.

Signed-off-by: Hugo Marchadour <hugo.marchadour@obeo.fr>